on:
  - push
  - pull_request
name: Unit test
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.7', '3.1' ]
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
    name: Test on ${{ matrix.os }} with Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install dependencies
        run: bundle
      - name: Run tests
        run: bundle exec rake test
